spring:
  application:
    name: sub
  profiles:
    active: @profileActive@

  mvc:
    view:
      prefix: /
      suffix: .html
    pathmatch:
      use-suffix-pattern: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml
