server:
  port: 9090
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
  servlet:
    context-path: /sub

spring:
  datasource:
    druid:
      #url: jdbc:mysql://172.16.140.105:3306/rs_dev?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      url: jdbc:mysql://172.16.140.105:3306/rs_dev?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      #url: jdbc:mysql://172.16.140.150:3306/rs_new_j?serverTimezone=Asia/Shanghai& characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: root
      #password: 12345678
      password: Vv12345!
      #password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
#info:
#  app:
#    name: spring-boot-actuator
#    version: 1.0.0
#    test: test
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true

